//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientBankSWNet.ProductWebService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://webServices/", ConfigurationName="ProductWebService.ProductWebService")]
    public interface ProductWebService {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://webServices/ProductWebService/updateProductRequest", ReplyAction="http://webServices/ProductWebService/updateProductResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ClientBankSWNet.ProductWebService.updateProductResponse updateProduct(ClientBankSWNet.ProductWebService.updateProductRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webServices/ProductWebService/updateProductRequest", ReplyAction="http://webServices/ProductWebService/updateProductResponse")]
        System.Threading.Tasks.Task<ClientBankSWNet.ProductWebService.updateProductResponse> updateProductAsync(ClientBankSWNet.ProductWebService.updateProductRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://webServices/ProductWebService/findProductRequest", ReplyAction="http://webServices/ProductWebService/findProductResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ClientBankSWNet.ProductWebService.findProductResponse findProduct(ClientBankSWNet.ProductWebService.findProductRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webServices/ProductWebService/findProductRequest", ReplyAction="http://webServices/ProductWebService/findProductResponse")]
        System.Threading.Tasks.Task<ClientBankSWNet.ProductWebService.findProductResponse> findProductAsync(ClientBankSWNet.ProductWebService.findProductRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://webServices/ProductWebService/insertProductRequest", ReplyAction="http://webServices/ProductWebService/insertProductResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ClientBankSWNet.ProductWebService.insertProductResponse insertProduct(ClientBankSWNet.ProductWebService.insertProductRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webServices/ProductWebService/insertProductRequest", ReplyAction="http://webServices/ProductWebService/insertProductResponse")]
        System.Threading.Tasks.Task<ClientBankSWNet.ProductWebService.insertProductResponse> insertProductAsync(ClientBankSWNet.ProductWebService.insertProductRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://webServices/ProductWebService/deleteProductRequest", ReplyAction="http://webServices/ProductWebService/deleteProductResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ClientBankSWNet.ProductWebService.deleteProductResponse deleteProduct(ClientBankSWNet.ProductWebService.deleteProductRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webServices/ProductWebService/deleteProductRequest", ReplyAction="http://webServices/ProductWebService/deleteProductResponse")]
        System.Threading.Tasks.Task<ClientBankSWNet.ProductWebService.deleteProductResponse> deleteProductAsync(ClientBankSWNet.ProductWebService.deleteProductRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://webServices/ProductWebService/listAllProductsRequest", ReplyAction="http://webServices/ProductWebService/listAllProductsResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ClientBankSWNet.ProductWebService.listAllProductsResponse listAllProducts(ClientBankSWNet.ProductWebService.listAllProductsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webServices/ProductWebService/listAllProductsRequest", ReplyAction="http://webServices/ProductWebService/listAllProductsResponse")]
        System.Threading.Tasks.Task<ClientBankSWNet.ProductWebService.listAllProductsResponse> listAllProductsAsync(ClientBankSWNet.ProductWebService.listAllProductsRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webServices/")]
    public partial class product : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int codeField;
        
        private string descField;
        
        private string nameField;
        
        private bool sateField;
        
        private string typeProductField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string desc {
            get {
                return this.descField;
            }
            set {
                this.descField = value;
                this.RaisePropertyChanged("desc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public bool sate {
            get {
                return this.sateField;
            }
            set {
                this.sateField = value;
                this.RaisePropertyChanged("sate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string typeProduct {
            get {
                return this.typeProductField;
            }
            set {
                this.typeProductField = value;
                this.RaisePropertyChanged("typeProduct");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="updateProduct", WrapperNamespace="http://webServices/", IsWrapped=true)]
    public partial class updateProductRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webServices/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webServices/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ClientBankSWNet.ProductWebService.product arg1;
        
        public updateProductRequest() {
        }
        
        public updateProductRequest(int arg0, ClientBankSWNet.ProductWebService.product arg1) {
            this.arg0 = arg0;
            this.arg1 = arg1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="updateProductResponse", WrapperNamespace="http://webServices/", IsWrapped=true)]
    public partial class updateProductResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webServices/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public updateProductResponse() {
        }
        
        public updateProductResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findProduct", WrapperNamespace="http://webServices/", IsWrapped=true)]
    public partial class findProductRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webServices/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg0;
        
        public findProductRequest() {
        }
        
        public findProductRequest(int arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findProductResponse", WrapperNamespace="http://webServices/", IsWrapped=true)]
    public partial class findProductResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webServices/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ClientBankSWNet.ProductWebService.product @return;
        
        public findProductResponse() {
        }
        
        public findProductResponse(ClientBankSWNet.ProductWebService.product @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertProduct", WrapperNamespace="http://webServices/", IsWrapped=true)]
    public partial class insertProductRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webServices/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ClientBankSWNet.ProductWebService.product arg0;
        
        public insertProductRequest() {
        }
        
        public insertProductRequest(ClientBankSWNet.ProductWebService.product arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertProductResponse", WrapperNamespace="http://webServices/", IsWrapped=true)]
    public partial class insertProductResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webServices/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public insertProductResponse() {
        }
        
        public insertProductResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="deleteProduct", WrapperNamespace="http://webServices/", IsWrapped=true)]
    public partial class deleteProductRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webServices/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg0;
        
        public deleteProductRequest() {
        }
        
        public deleteProductRequest(int arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="deleteProductResponse", WrapperNamespace="http://webServices/", IsWrapped=true)]
    public partial class deleteProductResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webServices/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public deleteProductResponse() {
        }
        
        public deleteProductResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listAllProducts", WrapperNamespace="http://webServices/", IsWrapped=true)]
    public partial class listAllProductsRequest {
        
        public listAllProductsRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listAllProductsResponse", WrapperNamespace="http://webServices/", IsWrapped=true)]
    public partial class listAllProductsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webServices/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ClientBankSWNet.ProductWebService.product[] @return;
        
        public listAllProductsResponse() {
        }
        
        public listAllProductsResponse(ClientBankSWNet.ProductWebService.product[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ProductWebServiceChannel : ClientBankSWNet.ProductWebService.ProductWebService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProductWebServiceClient : System.ServiceModel.ClientBase<ClientBankSWNet.ProductWebService.ProductWebService>, ClientBankSWNet.ProductWebService.ProductWebService {
        
        public ProductWebServiceClient() {
        }
        
        public ProductWebServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProductWebServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductWebServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductWebServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientBankSWNet.ProductWebService.updateProductResponse ClientBankSWNet.ProductWebService.ProductWebService.updateProduct(ClientBankSWNet.ProductWebService.updateProductRequest request) {
            return base.Channel.updateProduct(request);
        }
        
        public bool updateProduct(int arg0, ClientBankSWNet.ProductWebService.product arg1) {
            ClientBankSWNet.ProductWebService.updateProductRequest inValue = new ClientBankSWNet.ProductWebService.updateProductRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            ClientBankSWNet.ProductWebService.updateProductResponse retVal = ((ClientBankSWNet.ProductWebService.ProductWebService)(this)).updateProduct(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClientBankSWNet.ProductWebService.updateProductResponse> ClientBankSWNet.ProductWebService.ProductWebService.updateProductAsync(ClientBankSWNet.ProductWebService.updateProductRequest request) {
            return base.Channel.updateProductAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClientBankSWNet.ProductWebService.updateProductResponse> updateProductAsync(int arg0, ClientBankSWNet.ProductWebService.product arg1) {
            ClientBankSWNet.ProductWebService.updateProductRequest inValue = new ClientBankSWNet.ProductWebService.updateProductRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            return ((ClientBankSWNet.ProductWebService.ProductWebService)(this)).updateProductAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientBankSWNet.ProductWebService.findProductResponse ClientBankSWNet.ProductWebService.ProductWebService.findProduct(ClientBankSWNet.ProductWebService.findProductRequest request) {
            return base.Channel.findProduct(request);
        }
        
        public ClientBankSWNet.ProductWebService.product findProduct(int arg0) {
            ClientBankSWNet.ProductWebService.findProductRequest inValue = new ClientBankSWNet.ProductWebService.findProductRequest();
            inValue.arg0 = arg0;
            ClientBankSWNet.ProductWebService.findProductResponse retVal = ((ClientBankSWNet.ProductWebService.ProductWebService)(this)).findProduct(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClientBankSWNet.ProductWebService.findProductResponse> ClientBankSWNet.ProductWebService.ProductWebService.findProductAsync(ClientBankSWNet.ProductWebService.findProductRequest request) {
            return base.Channel.findProductAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClientBankSWNet.ProductWebService.findProductResponse> findProductAsync(int arg0) {
            ClientBankSWNet.ProductWebService.findProductRequest inValue = new ClientBankSWNet.ProductWebService.findProductRequest();
            inValue.arg0 = arg0;
            return ((ClientBankSWNet.ProductWebService.ProductWebService)(this)).findProductAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientBankSWNet.ProductWebService.insertProductResponse ClientBankSWNet.ProductWebService.ProductWebService.insertProduct(ClientBankSWNet.ProductWebService.insertProductRequest request) {
            return base.Channel.insertProduct(request);
        }
        
        public bool insertProduct(ClientBankSWNet.ProductWebService.product arg0) {
            ClientBankSWNet.ProductWebService.insertProductRequest inValue = new ClientBankSWNet.ProductWebService.insertProductRequest();
            inValue.arg0 = arg0;
            ClientBankSWNet.ProductWebService.insertProductResponse retVal = ((ClientBankSWNet.ProductWebService.ProductWebService)(this)).insertProduct(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClientBankSWNet.ProductWebService.insertProductResponse> ClientBankSWNet.ProductWebService.ProductWebService.insertProductAsync(ClientBankSWNet.ProductWebService.insertProductRequest request) {
            return base.Channel.insertProductAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClientBankSWNet.ProductWebService.insertProductResponse> insertProductAsync(ClientBankSWNet.ProductWebService.product arg0) {
            ClientBankSWNet.ProductWebService.insertProductRequest inValue = new ClientBankSWNet.ProductWebService.insertProductRequest();
            inValue.arg0 = arg0;
            return ((ClientBankSWNet.ProductWebService.ProductWebService)(this)).insertProductAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientBankSWNet.ProductWebService.deleteProductResponse ClientBankSWNet.ProductWebService.ProductWebService.deleteProduct(ClientBankSWNet.ProductWebService.deleteProductRequest request) {
            return base.Channel.deleteProduct(request);
        }
        
        public bool deleteProduct(int arg0) {
            ClientBankSWNet.ProductWebService.deleteProductRequest inValue = new ClientBankSWNet.ProductWebService.deleteProductRequest();
            inValue.arg0 = arg0;
            ClientBankSWNet.ProductWebService.deleteProductResponse retVal = ((ClientBankSWNet.ProductWebService.ProductWebService)(this)).deleteProduct(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClientBankSWNet.ProductWebService.deleteProductResponse> ClientBankSWNet.ProductWebService.ProductWebService.deleteProductAsync(ClientBankSWNet.ProductWebService.deleteProductRequest request) {
            return base.Channel.deleteProductAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClientBankSWNet.ProductWebService.deleteProductResponse> deleteProductAsync(int arg0) {
            ClientBankSWNet.ProductWebService.deleteProductRequest inValue = new ClientBankSWNet.ProductWebService.deleteProductRequest();
            inValue.arg0 = arg0;
            return ((ClientBankSWNet.ProductWebService.ProductWebService)(this)).deleteProductAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientBankSWNet.ProductWebService.listAllProductsResponse ClientBankSWNet.ProductWebService.ProductWebService.listAllProducts(ClientBankSWNet.ProductWebService.listAllProductsRequest request) {
            return base.Channel.listAllProducts(request);
        }
        
        public ClientBankSWNet.ProductWebService.product[] listAllProducts() {
            ClientBankSWNet.ProductWebService.listAllProductsRequest inValue = new ClientBankSWNet.ProductWebService.listAllProductsRequest();
            ClientBankSWNet.ProductWebService.listAllProductsResponse retVal = ((ClientBankSWNet.ProductWebService.ProductWebService)(this)).listAllProducts(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClientBankSWNet.ProductWebService.listAllProductsResponse> ClientBankSWNet.ProductWebService.ProductWebService.listAllProductsAsync(ClientBankSWNet.ProductWebService.listAllProductsRequest request) {
            return base.Channel.listAllProductsAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClientBankSWNet.ProductWebService.listAllProductsResponse> listAllProductsAsync() {
            ClientBankSWNet.ProductWebService.listAllProductsRequest inValue = new ClientBankSWNet.ProductWebService.listAllProductsRequest();
            return ((ClientBankSWNet.ProductWebService.ProductWebService)(this)).listAllProductsAsync(inValue);
        }
    }
}
