
package webservices;

import java.util.List;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;

import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10-b140319.1121
 * Generated source version: 2.2
 *
 */
@WebService(name = "ClientWebService", targetNamespace = "http://webServices/")
@XmlSeeAlso({ ObjectFactory.class })
public interface ClientWebService {


    /**
     *
     * @return
     *     returns java.util.List<webservices.Client>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listAllClients", targetNamespace = "http://webServices/",
                    className = "webservices.ListAllClients")
    @ResponseWrapper(localName = "listAllClientsResponse", targetNamespace = "http://webServices/",
                     className = "webservices.ListAllClientsResponse")
    @Action(input = "http://webServices/ClientWebService/listAllClientsRequest",
            output = "http://webServices/ClientWebService/listAllClientsResponse")
    public List<Client> listAllClients();

    /**
     *
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "updateClient", targetNamespace = "http://webServices/",
                    className = "webservices.UpdateClient")
    @ResponseWrapper(localName = "updateClientResponse", targetNamespace = "http://webServices/",
                     className = "webservices.UpdateClientResponse")
    @Action(input = "http://webServices/ClientWebService/updateClientRequest",
            output = "http://webServices/ClientWebService/updateClientResponse")
    public boolean updateClient(@WebParam(name = "arg0", targetNamespace = "") int arg0,
                                @WebParam(name = "arg1", targetNamespace = "") Client arg1);

    /**
     *
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "insertClient", targetNamespace = "http://webServices/",
                    className = "webservices.InsertClient")
    @ResponseWrapper(localName = "insertClientResponse", targetNamespace = "http://webServices/",
                     className = "webservices.InsertClientResponse")
    @Action(input = "http://webServices/ClientWebService/insertClientRequest",
            output = "http://webServices/ClientWebService/insertClientResponse")
    public boolean insertClient(@WebParam(name = "arg0", targetNamespace = "") Client arg0);

    /**
     *
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "deleteClient", targetNamespace = "http://webServices/",
                    className = "webservices.DeleteClient")
    @ResponseWrapper(localName = "deleteClientResponse", targetNamespace = "http://webServices/",
                     className = "webservices.DeleteClientResponse")
    @Action(input = "http://webServices/ClientWebService/deleteClientRequest",
            output = "http://webServices/ClientWebService/deleteClientResponse")
    public boolean deleteClient(@WebParam(name = "arg0", targetNamespace = "") int arg0);

    /**
     *
     * @param arg0
     * @return
     *     returns webservices.Client
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findClient", targetNamespace = "http://webServices/",
                    className = "webservices.FindClient")
    @ResponseWrapper(localName = "findClientResponse", targetNamespace = "http://webServices/",
                     className = "webservices.FindClientResponse")
    @Action(input = "http://webServices/ClientWebService/findClientRequest",
            output = "http://webServices/ClientWebService/findClientResponse")
    public Client findClient(@WebParam(name = "arg0", targetNamespace = "") int arg0);

}
