
package webservices;

import java.util.List;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;

import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10-b140319.1121
 * Generated source version: 2.2
 *
 */
@WebService(name = "ProductRegistrationWebService", targetNamespace = "http://webServices/")
@XmlSeeAlso({ ObjectFactory.class })
public interface ProductRegistrationWebService {


    /**
     *
     * @param arg1
     * @param arg0
     * @return
     *     returns webservices.ProductRegistration
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findProductoRegistration", targetNamespace = "http://webServices/",
                    className = "webservices.FindProductoRegistration")
    @ResponseWrapper(localName = "findProductoRegistrationResponse", targetNamespace = "http://webServices/",
                     className = "webservices.FindProductoRegistrationResponse")
    @Action(input = "http://webServices/ProductRegistrationWebService/findProductoRegistrationRequest",
            output = "http://webServices/ProductRegistrationWebService/findProductoRegistrationResponse")
    public ProductRegistration findProductoRegistration(@WebParam(name = "arg0", targetNamespace = "") int arg0,
                                                        @WebParam(name = "arg1", targetNamespace = "") int arg1);

    /**
     *
     * @return
     *     returns java.util.List<webservices.ProductRegistration>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listAllRegistrationService", targetNamespace = "http://webServices/",
                    className = "webservices.ListAllRegistrationService")
    @ResponseWrapper(localName = "listAllRegistrationServiceResponse", targetNamespace = "http://webServices/",
                     className = "webservices.ListAllRegistrationServiceResponse")
    @Action(input = "http://webServices/ProductRegistrationWebService/listAllRegistrationServiceRequest",
            output = "http://webServices/ProductRegistrationWebService/listAllRegistrationServiceResponse")
    public List<ProductRegistration> listAllRegistrationService();

    /**
     *
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "updateProductoRegistration", targetNamespace = "http://webServices/",
                    className = "webservices.UpdateProductoRegistration")
    @ResponseWrapper(localName = "updateProductoRegistrationResponse", targetNamespace = "http://webServices/",
                     className = "webservices.UpdateProductoRegistrationResponse")
    @Action(input = "http://webServices/ProductRegistrationWebService/updateProductoRegistrationRequest",
            output = "http://webServices/ProductRegistrationWebService/updateProductoRegistrationResponse")
    public boolean updateProductoRegistration(@WebParam(name = "arg0", targetNamespace = "") int arg0,
                                              @WebParam(name = "arg1", targetNamespace = "") int arg1,
                                              @WebParam(name = "arg2", targetNamespace = "") ProductRegistration arg2);

    /**
     *
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "deleteProductoRegistration", targetNamespace = "http://webServices/",
                    className = "webservices.DeleteProductoRegistration")
    @ResponseWrapper(localName = "deleteProductoRegistrationResponse", targetNamespace = "http://webServices/",
                     className = "webservices.DeleteProductoRegistrationResponse")
    @Action(input = "http://webServices/ProductRegistrationWebService/deleteProductoRegistrationRequest",
            output = "http://webServices/ProductRegistrationWebService/deleteProductoRegistrationResponse")
    public boolean deleteProductoRegistration(@WebParam(name = "arg0", targetNamespace = "") int arg0,
                                              @WebParam(name = "arg1", targetNamespace = "") int arg1);

    /**
     *
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "insertProductoRegistration", targetNamespace = "http://webServices/",
                    className = "webservices.InsertProductoRegistration")
    @ResponseWrapper(localName = "insertProductoRegistrationResponse", targetNamespace = "http://webServices/",
                     className = "webservices.InsertProductoRegistrationResponse")
    @Action(input = "http://webServices/ProductRegistrationWebService/insertProductoRegistrationRequest",
            output = "http://webServices/ProductRegistrationWebService/insertProductoRegistrationResponse")
    public boolean insertProductRegistration(@WebParam(name = "arg0", targetNamespace = "") ProductRegistration arg0);

}
