/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.ClientController;

import java.rmi.RemoteException;

import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

import webservices.Client;


/**
 *
 * @author Sherg
 */
public class GUIAddClient extends javax.swing.JFrame implements IObserver {

    private ClientController clientController;
    private Observer observer;

    /**
     * Creates new form GUIAddClient
     */
    public GUIAddClient(ClientController controller) {
        initComponents();
        labIconAddClient.setIcon(new ImageIcon("images/iconAddClient.png"));

        this.clientController = controller;
        this.observer = Observer.getIstance();
        observer.addObserver(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {//GEN-BEGIN:initComponents

        jLabIdNumber = new javax.swing.JLabel();
        jLabName = new javax.swing.JLabel();
        jLabBithday = new javax.swing.JLabel();
        jLabEmail = new javax.swing.JLabel();
        jLabPhoneNumber = new javax.swing.JLabel();
        jLabBalance = new javax.swing.JLabel();
        jTextFieldIdNumber = new javax.swing.JTextField();
        jTextFieldName = new javax.swing.JTextField();
        jTextFieldEmail = new javax.swing.JTextField();
        jTextFieldPhoneNumber = new javax.swing.JTextField();
        jButtonAddClient = new javax.swing.JButton();
        jDateChooserBirthday = new com.toedter.calendar.JDateChooser();
        labTitle = new javax.swing.JLabel();
        labIconAddClient = new javax.swing.JLabel();
        labDocType = new javax.swing.JLabel();
        jComboBoxDocType = new javax.swing.JComboBox();
        jComboBoxGender = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Agregar Cliente");
        setResizable(false);

        jLabIdNumber.setText("Número de Identificación:");

        jLabName.setText("Nombre:");

        jLabBithday.setText("Fecha de naciemiento:");

        jLabEmail.setText("E-mail:");

        jLabPhoneNumber.setText("Telefono:");

        jLabBalance.setText("Genero:");

        jButtonAddClient.setFont(new java.awt.Font("Lucida Handwriting", 0, 12)); // NOI18N
        jButtonAddClient.setText("Agregar Cliente");
        jButtonAddClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddClientActionPerformed(evt);
            }
        });

        labTitle.setFont(new java.awt.Font("Lucida Calligraphy", 0, 24)); // NOI18N
        labTitle.setText("Regristro de cliente");

        labDocType.setText("Típo de documento:");

        jComboBoxDocType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Cédula de ciudadanía", "Tarjeta de identidad", "Cédula de extranjería" }));

        jComboBoxGender.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Masculino", "Femenino", "Otro" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addComponent(labTitle)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labIconAddClient, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonAddClient)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabPhoneNumber)
                            .addComponent(jLabBalance)
                            .addComponent(jLabIdNumber)
                            .addComponent(jLabName)
                            .addComponent(jLabBithday)
                            .addComponent(jLabEmail)
                            .addComponent(labDocType))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldIdNumber)
                            .addComponent(jTextFieldName)
                            .addComponent(jTextFieldPhoneNumber)
                            .addComponent(jTextFieldEmail)
                            .addComponent(jDateChooserBirthday, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(jComboBoxDocType, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBoxGender, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labTitle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabIdNumber)
                            .addComponent(jTextFieldIdNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labDocType)
                            .addComponent(jComboBoxDocType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabName)
                            .addComponent(jTextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabBithday)
                            .addComponent(jDateChooserBirthday, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabEmail)
                            .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabPhoneNumber))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabBalance)
                            .addComponent(jComboBoxGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(labIconAddClient, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonAddClient)
                .addContainerGap())
        );

        pack();
    }//GEN-END:initComponents

    private void jButtonAddClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddClientActionPerformed

        String strIdNumber = jTextFieldIdNumber.getText().trim();
        String docType = jComboBoxDocType.getSelectedItem().toString().trim();
        String name = jTextFieldName.getText().trim();
        Date birthday = jDateChooserBirthday.getDate();
        String email = jTextFieldEmail.getText().trim();
        String phoneNumber = jTextFieldPhoneNumber.getText().trim();
        String gender = jComboBoxGender.getSelectedItem().toString().trim();

        try {
            boolean insert =
                this.clientController.addClient(strIdNumber, docType, name, birthday, email, phoneNumber, gender);
            if (insert) {
                JOptionPane.showMessageDialog(this, "EL cliente  ha sido agreagdo.", "Confirmación",
                                              JOptionPane.INFORMATION_MESSAGE);

                jTextFieldIdNumber.setText("");
                jTextFieldName.setText("");
                jDateChooserBirthday.setDate(null);
                jTextFieldEmail.setText("");
                jTextFieldPhoneNumber.setText("");
            } else {
                JOptionPane.showMessageDialog(this, "Ya existe un cliente con ese número de identificación.",
                                              "Advertencia", JOptionPane.WARNING_MESSAGE);
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Advertencia", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jButtonAddClientActionPerformed

    @Override
    public void update() {
        jTextFieldIdNumber.setText("");
        jTextFieldName.setText("");
        jDateChooserBirthday.setDate(null);
        jTextFieldEmail.setText("");
        jTextFieldPhoneNumber.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAddClient;
    private javax.swing.JComboBox jComboBoxDocType;
    private javax.swing.JComboBox jComboBoxGender;
    private com.toedter.calendar.JDateChooser jDateChooserBirthday;
    private javax.swing.JLabel jLabBalance;
    private javax.swing.JLabel jLabBithday;
    private javax.swing.JLabel jLabEmail;
    private javax.swing.JLabel jLabIdNumber;
    private javax.swing.JLabel jLabName;
    private javax.swing.JLabel jLabPhoneNumber;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldIdNumber;
    private javax.swing.JTextField jTextFieldName;
    private javax.swing.JTextField jTextFieldPhoneNumber;
    private javax.swing.JLabel labDocType;
    private javax.swing.JLabel labIconAddClient;
    private javax.swing.JLabel labTitle;
    // End of variables declaration//GEN-END:variables

}
