/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.ClientController;
import controller.ProductController;
import controller.ProductRegistrationController;

import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.JDialog;

import javax.swing.JOptionPane;

import webservices.Client;
import webservices.Product;
import webservices.ProductRegistration;

/**
 *
 * @author Sherg
 */
public class GUIDeleteProductRegistration extends javax.swing.JFrame implements ILoadModalData {

    private final ClientController clientController;
    private final ProductController productController;
    private final ProductRegistrationController productRegistrationController;

    private JDialog modal;

    private Client client;

    /**
     * Creates new form GUIDeleteProductRegistration
     */
    public GUIDeleteProductRegistration(ClientController pClientController, ProductController pProductController,
                                        ProductRegistrationController pProductRegistrationController) {
        initComponents();

        this.clientController = pClientController;
        this.productController = pProductController;
        this.productRegistrationController = pProductRegistrationController;

        this.client = null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {//GEN-BEGIN:initComponents

        labBalance = new javax.swing.JLabel();
        labProductNumber = new javax.swing.JLabel();
        labExpirationDate = new javax.swing.JLabel();
        labState = new javax.swing.JLabel();
        txtProductNumber = new javax.swing.JTextField();
        txtBalance = new javax.swing.JTextField();
        txtRegDate = new javax.swing.JTextField();
        txtExpDate = new javax.swing.JTextField();
        txtState = new javax.swing.JTextField();
        labTitle = new javax.swing.JLabel();
        labIdClient = new javax.swing.JLabel();
        txtIdClient = new javax.swing.JTextField();
        btnFindClient = new javax.swing.JButton();
        labProductCode = new javax.swing.JLabel();
        jComboBoxProductCode = new javax.swing.JComboBox<String>();
        btnBuscar = new javax.swing.JButton();
        labRegistrrionDate = new javax.swing.JLabel();
        btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Eliminar registro");

        labBalance.setText("Saldo:");

        labProductNumber.setText("Número de producto:");

        labExpirationDate.setText("Fecha de vencimiento:");

        labState.setText("Estado:");

        labTitle.setFont(new java.awt.Font("Lucida Calligraphy", 0, 24)); // NOI18N
        labTitle.setText("Eliminar Registro");

        labIdClient.setText("Documento del Cliente:");

        btnFindClient.setText("...");
        btnFindClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindClientActionPerformed(evt);
            }
        });

        labProductCode.setText("Código de producto:");

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        labRegistrrionDate.setText("Fecha de expedición:");

        btn.setText("Eliminar registro");
        btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(labIdClient, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labProductCode)
                    .addComponent(labProductNumber, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labBalance, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labRegistrrionDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labExpirationDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labState, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtIdClient, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnFindClient, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtExpDate)
                    .addComponent(txtRegDate)
                    .addComponent(txtBalance)
                    .addComponent(txtProductNumber)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jComboBoxProductCode, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnBuscar))
                    .addComponent(txtState))
                .addContainerGap(19, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btn)
                .addGap(159, 159, 159))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labTitle)
                .addGap(97, 97, 97))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(labTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labIdClient)
                    .addComponent(txtIdClient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFindClient))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labProductCode)
                    .addComponent(jComboBoxProductCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtProductNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labProductNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtBalance)
                    .addComponent(labBalance, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labRegistrrionDate, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtRegDate, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtExpDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(labExpirationDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtState)
                    .addComponent(labState, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(btn)
                .addContainerGap())
        );

        pack();
    }//GEN-END:initComponents

    private void btnFindClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindClientActionPerformed
        GUIPanelModalListClients panel = new GUIPanelModalListClients(this, this.clientController);
        modal = new JDialog(this, "Clientes", true);
        modal.getContentPane().add(panel);
        modal.pack();
        modal.setLocationRelativeTo(null);
        modal.setVisible(true);
    }//GEN-LAST:event_btnFindClientActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        String strProductCode = jComboBoxProductCode.getSelectedItem().toString();

        try {
            ProductRegistration productRegistrartion =
                this.productRegistrationController.findProductRegistration(client.getIdentificationNumber(),
                                                                           strProductCode);

            txtProductNumber.setText(String.valueOf(productRegistrartion.getProductNumber()));
            txtBalance.setText(String.valueOf(productRegistrartion.getBalance()));
            txtRegDate.setText(String.valueOf(productRegistrartion.getRegistratioDate()));
            txtExpDate.setText(String.valueOf(productRegistrartion.getExpirationDate()));
            txtState.setText((productRegistrartion.isState() ? "Activo" : "Inactivo"));

            txtProductNumber.setEditable(false);
            txtBalance.setEditable(false);
            txtRegDate.setEditable(false);
            txtExpDate.setEditable(false);
            txtState.setEditable(false);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Advertencia", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActionPerformed
        String strProductCode = jComboBoxProductCode.getSelectedItem().toString();

        try {
            boolean delete =
                this.productRegistrationController.deleteProductRegistration(client.getIdentificationNumber(),
                                                                             strProductCode);
            if (delete) {
                JOptionPane.showMessageDialog(this, "El registro se ha eliminado correctamente.", "Confirmación",
                                              JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "No se ha podido eliminar el registro.", "Eror",
                                              JOptionPane.ERROR_MESSAGE);
                txtIdClient.setText(null);
                jComboBoxProductCode.setSelectedIndex(0);
                txtProductNumber.setText("");
                txtBalance.setText("");
                txtRegDate.setText("");
                txtExpDate.setText("");
                txtState.setText("");
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Advertencia", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnActionPerformed

    public void loadData() {
        jComboBoxProductCode.removeAllItems();
        List<ProductRegistration> allProductRegistrations =
            this.productRegistrationController.listAllProductRegistrations();
        List<ProductRegistration> clientProductRegistrations = new ArrayList<>();

        for (ProductRegistration productRegistration : allProductRegistrations) {
            if (productRegistration.getClientId() == client.getIdentificationNumber()) {
                clientProductRegistrations.add(productRegistration);
            }
        }

        jComboBoxProductCode.addItem("");
        for (ProductRegistration clientProductRegistration : clientProductRegistrations) {
            try {
                Product product = this.productController.findProductById(clientProductRegistration.getProductCode());
                jComboBoxProductCode.addItem(String.valueOf(product.getCode()));
            } catch (Exception ex) {
                Logger.getLogger(GUIFindProductRegistration.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }

    @Override
    public void loadModalData(String data) {
        txtIdClient.setText(data);
        modal.dispose();
        txtIdClient.setEditable(false);

        try {
            client = clientController.findClientById(data);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
        this.loadData();
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnFindClient;
    private javax.swing.JComboBox<String> jComboBoxProductCode;
    private javax.swing.JLabel labBalance;
    private javax.swing.JLabel labExpirationDate;
    private javax.swing.JLabel labIdClient;
    private javax.swing.JLabel labProductCode;
    private javax.swing.JLabel labProductNumber;
    private javax.swing.JLabel labRegistrrionDate;
    private javax.swing.JLabel labState;
    private javax.swing.JLabel labTitle;
    private javax.swing.JTextField txtBalance;
    private javax.swing.JTextField txtExpDate;
    private javax.swing.JTextField txtIdClient;
    private javax.swing.JTextField txtProductNumber;
    private javax.swing.JTextField txtRegDate;
    private javax.swing.JTextField txtState;
    // End of variables declaration//GEN-END:variables

}
