//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientBankSWNet.ClientWebService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://webServices/", ConfigurationName="ClientWebService.ClientWebService")]
    public interface ClientWebService {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://webServices/ClientWebService/insertClientRequest", ReplyAction="http://webServices/ClientWebService/insertClientResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ClientBankSWNet.ClientWebService.insertClientResponse insertClient(ClientBankSWNet.ClientWebService.insertClientRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webServices/ClientWebService/insertClientRequest", ReplyAction="http://webServices/ClientWebService/insertClientResponse")]
        System.Threading.Tasks.Task<ClientBankSWNet.ClientWebService.insertClientResponse> insertClientAsync(ClientBankSWNet.ClientWebService.insertClientRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://webServices/ClientWebService/deleteClientRequest", ReplyAction="http://webServices/ClientWebService/deleteClientResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ClientBankSWNet.ClientWebService.deleteClientResponse deleteClient(ClientBankSWNet.ClientWebService.deleteClientRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webServices/ClientWebService/deleteClientRequest", ReplyAction="http://webServices/ClientWebService/deleteClientResponse")]
        System.Threading.Tasks.Task<ClientBankSWNet.ClientWebService.deleteClientResponse> deleteClientAsync(ClientBankSWNet.ClientWebService.deleteClientRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://webServices/ClientWebService/findClientRequest", ReplyAction="http://webServices/ClientWebService/findClientResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ClientBankSWNet.ClientWebService.findClientResponse findClient(ClientBankSWNet.ClientWebService.findClientRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webServices/ClientWebService/findClientRequest", ReplyAction="http://webServices/ClientWebService/findClientResponse")]
        System.Threading.Tasks.Task<ClientBankSWNet.ClientWebService.findClientResponse> findClientAsync(ClientBankSWNet.ClientWebService.findClientRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://webServices/ClientWebService/updateClientRequest", ReplyAction="http://webServices/ClientWebService/updateClientResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ClientBankSWNet.ClientWebService.updateClientResponse updateClient(ClientBankSWNet.ClientWebService.updateClientRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webServices/ClientWebService/updateClientRequest", ReplyAction="http://webServices/ClientWebService/updateClientResponse")]
        System.Threading.Tasks.Task<ClientBankSWNet.ClientWebService.updateClientResponse> updateClientAsync(ClientBankSWNet.ClientWebService.updateClientRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://webServices/ClientWebService/listAllClientsRequest", ReplyAction="http://webServices/ClientWebService/listAllClientsResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ClientBankSWNet.ClientWebService.listAllClientsResponse listAllClients(ClientBankSWNet.ClientWebService.listAllClientsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webServices/ClientWebService/listAllClientsRequest", ReplyAction="http://webServices/ClientWebService/listAllClientsResponse")]
        System.Threading.Tasks.Task<ClientBankSWNet.ClientWebService.listAllClientsResponse> listAllClientsAsync(ClientBankSWNet.ClientWebService.listAllClientsRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webServices/")]
    public partial class client : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.DateTime birthdayField;
        
        private bool birthdayFieldSpecified;
        
        private string documetTypeField;
        
        private string emailField;
        
        private string genderField;
        
        private int identificationNumberField;
        
        private string nameField;
        
        private string phoneNumberField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date", Order=0)]
        public System.DateTime birthday {
            get {
                return this.birthdayField;
            }
            set {
                this.birthdayField = value;
                this.RaisePropertyChanged("birthday");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool birthdaySpecified {
            get {
                return this.birthdayFieldSpecified;
            }
            set {
                this.birthdayFieldSpecified = value;
                this.RaisePropertyChanged("birthdaySpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string documetType {
            get {
                return this.documetTypeField;
            }
            set {
                this.documetTypeField = value;
                this.RaisePropertyChanged("documetType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
                this.RaisePropertyChanged("email");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string gender {
            get {
                return this.genderField;
            }
            set {
                this.genderField = value;
                this.RaisePropertyChanged("gender");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int identificationNumber {
            get {
                return this.identificationNumberField;
            }
            set {
                this.identificationNumberField = value;
                this.RaisePropertyChanged("identificationNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string phoneNumber {
            get {
                return this.phoneNumberField;
            }
            set {
                this.phoneNumberField = value;
                this.RaisePropertyChanged("phoneNumber");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertClient", WrapperNamespace="http://webServices/", IsWrapped=true)]
    public partial class insertClientRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webServices/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ClientBankSWNet.ClientWebService.client arg0;
        
        public insertClientRequest() {
        }
        
        public insertClientRequest(ClientBankSWNet.ClientWebService.client arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertClientResponse", WrapperNamespace="http://webServices/", IsWrapped=true)]
    public partial class insertClientResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webServices/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public insertClientResponse() {
        }
        
        public insertClientResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="deleteClient", WrapperNamespace="http://webServices/", IsWrapped=true)]
    public partial class deleteClientRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webServices/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg0;
        
        public deleteClientRequest() {
        }
        
        public deleteClientRequest(int arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="deleteClientResponse", WrapperNamespace="http://webServices/", IsWrapped=true)]
    public partial class deleteClientResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webServices/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public deleteClientResponse() {
        }
        
        public deleteClientResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findClient", WrapperNamespace="http://webServices/", IsWrapped=true)]
    public partial class findClientRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webServices/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg0;
        
        public findClientRequest() {
        }
        
        public findClientRequest(int arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findClientResponse", WrapperNamespace="http://webServices/", IsWrapped=true)]
    public partial class findClientResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webServices/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ClientBankSWNet.ClientWebService.client @return;
        
        public findClientResponse() {
        }
        
        public findClientResponse(ClientBankSWNet.ClientWebService.client @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="updateClient", WrapperNamespace="http://webServices/", IsWrapped=true)]
    public partial class updateClientRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webServices/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webServices/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ClientBankSWNet.ClientWebService.client arg1;
        
        public updateClientRequest() {
        }
        
        public updateClientRequest(int arg0, ClientBankSWNet.ClientWebService.client arg1) {
            this.arg0 = arg0;
            this.arg1 = arg1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="updateClientResponse", WrapperNamespace="http://webServices/", IsWrapped=true)]
    public partial class updateClientResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webServices/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public updateClientResponse() {
        }
        
        public updateClientResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listAllClients", WrapperNamespace="http://webServices/", IsWrapped=true)]
    public partial class listAllClientsRequest {
        
        public listAllClientsRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listAllClientsResponse", WrapperNamespace="http://webServices/", IsWrapped=true)]
    public partial class listAllClientsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webServices/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ClientBankSWNet.ClientWebService.client[] @return;
        
        public listAllClientsResponse() {
        }
        
        public listAllClientsResponse(ClientBankSWNet.ClientWebService.client[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ClientWebServiceChannel : ClientBankSWNet.ClientWebService.ClientWebService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ClientWebServiceClient : System.ServiceModel.ClientBase<ClientBankSWNet.ClientWebService.ClientWebService>, ClientBankSWNet.ClientWebService.ClientWebService {
        
        public ClientWebServiceClient() {
        }
        
        public ClientWebServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ClientWebServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ClientWebServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ClientWebServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientBankSWNet.ClientWebService.insertClientResponse ClientBankSWNet.ClientWebService.ClientWebService.insertClient(ClientBankSWNet.ClientWebService.insertClientRequest request) {
            return base.Channel.insertClient(request);
        }
        
        public bool insertClient(ClientBankSWNet.ClientWebService.client arg0) {
            ClientBankSWNet.ClientWebService.insertClientRequest inValue = new ClientBankSWNet.ClientWebService.insertClientRequest();
            inValue.arg0 = arg0;
            ClientBankSWNet.ClientWebService.insertClientResponse retVal = ((ClientBankSWNet.ClientWebService.ClientWebService)(this)).insertClient(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClientBankSWNet.ClientWebService.insertClientResponse> ClientBankSWNet.ClientWebService.ClientWebService.insertClientAsync(ClientBankSWNet.ClientWebService.insertClientRequest request) {
            return base.Channel.insertClientAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClientBankSWNet.ClientWebService.insertClientResponse> insertClientAsync(ClientBankSWNet.ClientWebService.client arg0) {
            ClientBankSWNet.ClientWebService.insertClientRequest inValue = new ClientBankSWNet.ClientWebService.insertClientRequest();
            inValue.arg0 = arg0;
            return ((ClientBankSWNet.ClientWebService.ClientWebService)(this)).insertClientAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientBankSWNet.ClientWebService.deleteClientResponse ClientBankSWNet.ClientWebService.ClientWebService.deleteClient(ClientBankSWNet.ClientWebService.deleteClientRequest request) {
            return base.Channel.deleteClient(request);
        }
        
        public bool deleteClient(int arg0) {
            ClientBankSWNet.ClientWebService.deleteClientRequest inValue = new ClientBankSWNet.ClientWebService.deleteClientRequest();
            inValue.arg0 = arg0;
            ClientBankSWNet.ClientWebService.deleteClientResponse retVal = ((ClientBankSWNet.ClientWebService.ClientWebService)(this)).deleteClient(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClientBankSWNet.ClientWebService.deleteClientResponse> ClientBankSWNet.ClientWebService.ClientWebService.deleteClientAsync(ClientBankSWNet.ClientWebService.deleteClientRequest request) {
            return base.Channel.deleteClientAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClientBankSWNet.ClientWebService.deleteClientResponse> deleteClientAsync(int arg0) {
            ClientBankSWNet.ClientWebService.deleteClientRequest inValue = new ClientBankSWNet.ClientWebService.deleteClientRequest();
            inValue.arg0 = arg0;
            return ((ClientBankSWNet.ClientWebService.ClientWebService)(this)).deleteClientAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientBankSWNet.ClientWebService.findClientResponse ClientBankSWNet.ClientWebService.ClientWebService.findClient(ClientBankSWNet.ClientWebService.findClientRequest request) {
            return base.Channel.findClient(request);
        }
        
        public ClientBankSWNet.ClientWebService.client findClient(int arg0) {
            ClientBankSWNet.ClientWebService.findClientRequest inValue = new ClientBankSWNet.ClientWebService.findClientRequest();
            inValue.arg0 = arg0;
            ClientBankSWNet.ClientWebService.findClientResponse retVal = ((ClientBankSWNet.ClientWebService.ClientWebService)(this)).findClient(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClientBankSWNet.ClientWebService.findClientResponse> ClientBankSWNet.ClientWebService.ClientWebService.findClientAsync(ClientBankSWNet.ClientWebService.findClientRequest request) {
            return base.Channel.findClientAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClientBankSWNet.ClientWebService.findClientResponse> findClientAsync(int arg0) {
            ClientBankSWNet.ClientWebService.findClientRequest inValue = new ClientBankSWNet.ClientWebService.findClientRequest();
            inValue.arg0 = arg0;
            return ((ClientBankSWNet.ClientWebService.ClientWebService)(this)).findClientAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientBankSWNet.ClientWebService.updateClientResponse ClientBankSWNet.ClientWebService.ClientWebService.updateClient(ClientBankSWNet.ClientWebService.updateClientRequest request) {
            return base.Channel.updateClient(request);
        }
        
        public bool updateClient(int arg0, ClientBankSWNet.ClientWebService.client arg1) {
            ClientBankSWNet.ClientWebService.updateClientRequest inValue = new ClientBankSWNet.ClientWebService.updateClientRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            ClientBankSWNet.ClientWebService.updateClientResponse retVal = ((ClientBankSWNet.ClientWebService.ClientWebService)(this)).updateClient(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClientBankSWNet.ClientWebService.updateClientResponse> ClientBankSWNet.ClientWebService.ClientWebService.updateClientAsync(ClientBankSWNet.ClientWebService.updateClientRequest request) {
            return base.Channel.updateClientAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClientBankSWNet.ClientWebService.updateClientResponse> updateClientAsync(int arg0, ClientBankSWNet.ClientWebService.client arg1) {
            ClientBankSWNet.ClientWebService.updateClientRequest inValue = new ClientBankSWNet.ClientWebService.updateClientRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            return ((ClientBankSWNet.ClientWebService.ClientWebService)(this)).updateClientAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientBankSWNet.ClientWebService.listAllClientsResponse ClientBankSWNet.ClientWebService.ClientWebService.listAllClients(ClientBankSWNet.ClientWebService.listAllClientsRequest request) {
            return base.Channel.listAllClients(request);
        }
        
        public ClientBankSWNet.ClientWebService.client[] listAllClients() {
            ClientBankSWNet.ClientWebService.listAllClientsRequest inValue = new ClientBankSWNet.ClientWebService.listAllClientsRequest();
            ClientBankSWNet.ClientWebService.listAllClientsResponse retVal = ((ClientBankSWNet.ClientWebService.ClientWebService)(this)).listAllClients(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClientBankSWNet.ClientWebService.listAllClientsResponse> ClientBankSWNet.ClientWebService.ClientWebService.listAllClientsAsync(ClientBankSWNet.ClientWebService.listAllClientsRequest request) {
            return base.Channel.listAllClientsAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClientBankSWNet.ClientWebService.listAllClientsResponse> listAllClientsAsync() {
            ClientBankSWNet.ClientWebService.listAllClientsRequest inValue = new ClientBankSWNet.ClientWebService.listAllClientsRequest();
            return ((ClientBankSWNet.ClientWebService.ClientWebService)(this)).listAllClientsAsync(inValue);
        }
    }
}
