/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.ClientController;
import controller.ProductController;
import controller.ProductRegistrationController;

import java.util.Date;
import java.util.List;

import javax.swing.JDialog;
import javax.swing.JOptionPane;

import webservices.Client;
import webservices.Product;


/**
 *
 * @author Sherg
 */
public class GUIAddProductRegistration extends javax.swing.JFrame implements ILoadModalData {

    private final ClientController clientController;
    private final ProductController productController;
    private final ProductRegistrationController productRegistrationController;

    private JDialog modal;

    private Client client;
    private Product product;

    /**
     * Creates new form GUIAddReg
     */
    public GUIAddProductRegistration(ClientController pClientController, ProductController pProductController,
                                     ProductRegistrationController pProductRegistrationController) {
        initComponents();

        this.clientController = pClientController;
        this.productController = pProductController;
        this.productRegistrationController = pProductRegistrationController;

        this.client = null;
        this.product = null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {//GEN-BEGIN:initComponents

        jPanel1 = new javax.swing.JPanel();
        txtIdClient = new javax.swing.JTextField();
        labState = new javax.swing.JLabel();
        txtProductNumber = new javax.swing.JTextField();
        txtBalance = new javax.swing.JTextField();
        btnFindClient = new javax.swing.JButton();
        labProductCode = new javax.swing.JLabel();
        jComboBoxProductCode = new javax.swing.JComboBox<String>();
        labRegistrrionDate = new javax.swing.JLabel();
        btnRegistrar = new javax.swing.JButton();
        labBalance = new javax.swing.JLabel();
        labProductNumber = new javax.swing.JLabel();
        labExpirationDate = new javax.swing.JLabel();
        labTitle = new javax.swing.JLabel();
        labIdClient = new javax.swing.JLabel();
        dateReg = new com.toedter.calendar.JDateChooser();
        dateExp = new com.toedter.calendar.JDateChooser();
        radBtnActivo = new javax.swing.JRadioButton();
        radBtnInactivo = new javax.swing.JRadioButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Registrar Producto");

        labState.setText("Estado:");

        btnFindClient.setText("...");
        btnFindClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindClientActionPerformed(evt);
            }
        });

        labProductCode.setText("Producto:");
        labProductCode.setToolTipText("");

        labRegistrrionDate.setText("Fecha de expedición:");

        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        labBalance.setText("Saldo:");

        labProductNumber.setText("Número de producto:");

        labExpirationDate.setText("Fecha de vencimiento:");

        labTitle.setFont(new java.awt.Font("Lucida Calligraphy", 0, 24)); // NOI18N
        labTitle.setText("Registrar Producto");
        labTitle.setToolTipText("");

        labIdClient.setText("Documento del Cliente:");

        radBtnActivo.setSelected(true);
        radBtnActivo.setText("Avtivo");
        radBtnActivo.setToolTipText("");

        radBtnInactivo.setText("Inactivo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(labIdClient, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labProductCode)
                    .addComponent(labProductNumber, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labBalance, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labRegistrrionDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labExpirationDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labState, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtProductNumber)
                    .addComponent(txtBalance)
                    .addComponent(jComboBoxProductCode, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(txtIdClient, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnFindClient, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(dateReg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(dateExp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(radBtnActivo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(radBtnInactivo)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnRegistrar)
                        .addGap(171, 171, 171))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(labTitle)
                        .addGap(92, 92, 92))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labIdClient)
                    .addComponent(txtIdClient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFindClient))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labProductCode)
                    .addComponent(jComboBoxProductCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtProductNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labProductNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtBalance)
                    .addComponent(labBalance, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labRegistrrionDate, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dateReg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labExpirationDate, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dateExp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labState, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(radBtnActivo)
                        .addComponent(radBtnInactivo)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnRegistrar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }//GEN-END:initComponents

    private void btnFindClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindClientActionPerformed
        GUIPanelModalListClients panel = new GUIPanelModalListClients(this, this.clientController);
        modal = new JDialog(this, "Clientes", true);
        modal.getContentPane().add(panel);
        modal.pack();
        modal.setLocationRelativeTo(null);
        modal.setVisible(true);
    }//GEN-LAST:event_btnFindClientActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        int idClient = Integer.parseInt(txtIdClient.getText());
        List<Product> listProducts = null;

        listProducts = this.productController.listAllProducts();

        for (Product product : listProducts) {
            String str = (String) jComboBoxProductCode.getSelectedItem().toString();
            if (product.getName().equals(str)) {
                this.product = product;
            }
        }
        
        int productCode = product.getCode();
        String strProductNumber = txtProductNumber.getText();
        String strBalance = txtBalance.getText();
        Date registrationDate = dateReg.getDate();
        Date expirationDate = dateExp.getDate();
        boolean state = radBtnActivo.isSelected();

        try {
            boolean insert =
                this.productRegistrationController.addProductRegistration(idClient, productCode, strProductNumber,
                                                                          strBalance, registrationDate, expirationDate,
                                                                          state);

            if (insert) {
                JOptionPane.showMessageDialog(this, "Producto registrado correctamente.", "Confirmación",
                                              JOptionPane.INFORMATION_MESSAGE);
                txtProductNumber.setText("");
                txtBalance.setText("");
                dateReg.setDate(null);
                dateExp.setDate(null);
            } else {
                JOptionPane.showMessageDialog(this, "No se ha podido registrar el producto.", "Error",
                                              JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Advertencia", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnRegistrarActionPerformed

    public void loadProducts() {
        List<Product> productList = productController.listAllProducts();

        for (Product product : productList) {
            jComboBoxProductCode.addItem(product.getName());
        }
    }

    @Override
    public void loadModalData(String data) {
        txtIdClient.setText(data);
        modal.dispose();
        txtIdClient.setEditable(false);

        try {
            client = clientController.findClientById(data);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }

        loadProducts();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFindClient;
    private javax.swing.JButton btnRegistrar;
    private com.toedter.calendar.JDateChooser dateExp;
    private com.toedter.calendar.JDateChooser dateReg;
    private javax.swing.JComboBox<String> jComboBoxProductCode;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labBalance;
    private javax.swing.JLabel labExpirationDate;
    private javax.swing.JLabel labIdClient;
    private javax.swing.JLabel labProductCode;
    private javax.swing.JLabel labProductNumber;
    private javax.swing.JLabel labRegistrrionDate;
    private javax.swing.JLabel labState;
    private javax.swing.JLabel labTitle;
    private javax.swing.JRadioButton radBtnActivo;
    private javax.swing.JRadioButton radBtnInactivo;
    private javax.swing.JTextField txtBalance;
    private javax.swing.JTextField txtIdClient;
    private javax.swing.JTextField txtProductNumber;
    // End of variables declaration//GEN-END:variables

}
