/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.ClientController;

import java.text.SimpleDateFormat;

import java.util.List;

import javax.swing.table.DefaultTableModel;

import webservices.Client;

/**
 *
 * @author Sherg
 */
public class GUIPanelModalListClients extends javax.swing.JPanel {

    private ILoadModalData father;
    private final ClientController clientController;

    /**
     * Creates new form GUIPanelModalListClients
     * @param pClientService
     */
    public GUIPanelModalListClients(ILoadModalData pFather, ClientController contoller) {
        initComponents();
        this.clientController = contoller;
        this.father = pFather;
        this.loadDataTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableListClients = new javax.swing.JTable();

        setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Lista de Clientes", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        jTableListClients.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Número de identificación", "Tipo de documento", "Nombre", "Fecha de nacimiento", "E-mail", "Telefono", "Genero"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableListClients.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableListClientsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableListClients);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 615, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 263, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTableListClientsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableListClientsMouseClicked
        int column = 0;
        int row = jTableListClients.getSelectedRow();
        String value = jTableListClients.getModel().getValueAt(row, column).toString();
        father.loadModalData(value);
    }//GEN-LAST:event_jTableListClientsMouseClicked

    public void loadDataTable() {
        List<Client> clients = this.clientController.listAllClients();

        DefaultTableModel model = (DefaultTableModel) jTableListClients.getModel();
        model.setRowCount(0);

        for (Client client : clients) {
            model.addRow(new Object[] {
                         client.getIdentificationNumber(), client.getDocumetType(), client.getName(),
                         String.valueOf(client.getBirthday()), client.getEmail(), client.getPhoneNumber(),
                         client.getGender()
            });
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableListClients;
    // End of variables declaration//GEN-END:variables
}
