# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUIAddClient.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!

import sys
from PyQt5 import QtCore, QtGui, QtWidgets
from controller import client_controller

class Ui_GUI_Add_Client(object):
    def setupUi(self, GUI_Add_Client):
        GUI_Add_Client.setObjectName("GUI_Add_Client")
        GUI_Add_Client.resize(575, 360)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(GUI_Add_Client.sizePolicy().hasHeightForWidth())
        GUI_Add_Client.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(GUI_Add_Client)
        self.centralwidget.setObjectName("centralwidget")
        self.btn_add_client = QtWidgets.QPushButton(self.centralwidget)
        self.btn_add_client.setGeometry(QtCore.QRect(180, 290, 211, 51))
        font = QtGui.QFont()
        font.setFamily("Lucida Handwriting")
        font.setPointSize(16)
        self.btn_add_client.setFont(font)
        self.btn_add_client.setObjectName("btn_add_client")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(70, 70, 191, 201))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_id_number = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_id_number.setFont(font)
        self.label_id_number.setObjectName("label_id_number")
        self.verticalLayout.addWidget(self.label_id_number)
        self.label_doc_type = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_doc_type.setFont(font)
        self.label_doc_type.setObjectName("label_doc_type")
        self.verticalLayout.addWidget(self.label_doc_type)
        self.label_name = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_name.setFont(font)
        self.label_name.setObjectName("label_name")
        self.verticalLayout.addWidget(self.label_name)
        self.label_birthday = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_birthday.setFont(font)
        self.label_birthday.setObjectName("label_birthday")
        self.verticalLayout.addWidget(self.label_birthday)
        self.label_email = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_email.setFont(font)
        self.label_email.setObjectName("label_email")
        self.verticalLayout.addWidget(self.label_email)
        self.label_phone = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_phone.setFont(font)
        self.label_phone.setObjectName("label_phone")
        self.verticalLayout.addWidget(self.label_phone)
        self.label_gender = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_gender.setFont(font)
        self.label_gender.setObjectName("label_gender")
        self.verticalLayout.addWidget(self.label_gender)
        self.txt_id_number = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.txt_id_number.setGeometry(QtCore.QRect(270, 70, 259, 24))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txt_id_number.sizePolicy().hasHeightForWidth())
        self.txt_id_number.setSizePolicy(sizePolicy)
        self.txt_id_number.setObjectName("txt_id_number")
        self.comboBox_doc_type = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_doc_type.setGeometry(QtCore.QRect(270, 100, 259, 24))
        self.comboBox_doc_type.setObjectName("comboBox_doc_type")
        self.txt_name = QtWidgets.QTextEdit(self.centralwidget)
        self.txt_name.setGeometry(QtCore.QRect(270, 130, 259, 24))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txt_name.sizePolicy().hasHeightForWidth())
        self.txt_name.setSizePolicy(sizePolicy)
        self.txt_name.setObjectName("txt_name")
        self.dateEdit_birthday = QtWidgets.QDateEdit(self.centralwidget)
        self.dateEdit_birthday.setGeometry(QtCore.QRect(270, 160, 259, 24))
        self.dateEdit_birthday.setObjectName("dateEdit_birthday")
        self.txt_email = QtWidgets.QTextEdit(self.centralwidget)
        self.txt_email.setGeometry(QtCore.QRect(270, 190, 259, 24))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txt_email.sizePolicy().hasHeightForWidth())
        self.txt_email.setSizePolicy(sizePolicy)
        self.txt_email.setObjectName("txt_email")
        self.txt_phone_number = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.txt_phone_number.setGeometry(QtCore.QRect(270, 220, 259, 24))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txt_phone_number.sizePolicy().hasHeightForWidth())
        self.txt_phone_number.setSizePolicy(sizePolicy)
        self.txt_phone_number.setObjectName("txt_phone_number")
        self.comboBox_gender = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_gender.setGeometry(QtCore.QRect(270, 250, 259, 24))
        self.comboBox_gender.setObjectName("comboBox_gender")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 10, 571, 51))
        font = QtGui.QFont()
        font.setFamily("Lucida Handwriting")
        font.setPointSize(24)
        self.label.setFont(font)
        self.label.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        GUI_Add_Client.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(GUI_Add_Client)
        self.statusbar.setObjectName("statusbar")
        GUI_Add_Client.setStatusBar(self.statusbar)

        self.retranslateUi(GUI_Add_Client)
        QtCore.QMetaObject.connectSlotsByName(GUI_Add_Client)
        
        

    def retranslateUi(self, GUI_Add_Client):
        _translate = QtCore.QCoreApplication.translate
        GUI_Add_Client.setWindowTitle(_translate("GUI_Add_Client", "Agregar cliente"))
        self.btn_add_client.setText(_translate("GUI_Add_Client", "Agregar Cliente"))
        self.label_id_number.setText(_translate("GUI_Add_Client", "Número de Identificación:"))
        self.label_doc_type.setText(_translate("GUI_Add_Client", "Tipo de documento:"))
        self.label_name.setText(_translate("GUI_Add_Client", "Nombre:"))
        self.label_birthday.setText(_translate("GUI_Add_Client", "Fecha de nacimiento:"))
        self.label_email.setText(_translate("GUI_Add_Client", "E-mail:"))
        self.label_phone.setText(_translate("GUI_Add_Client", "Teléfono:"))
        self.label_gender.setText(_translate("GUI_Add_Client", "Género:"))
        self.label.setText(_translate("GUI_Add_Client", "Agregar Cliente"))
