
package webservices;

import java.util.List;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;

import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10-b140319.1121
 * Generated source version: 2.2
 *
 */
@WebService(name = "ProductWebService", targetNamespace = "http://webServices/")
@XmlSeeAlso({ ObjectFactory.class })
public interface ProductWebService {


    /**
     *
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "updateProduct", targetNamespace = "http://webServices/",
                    className = "webservices.UpdateProduct")
    @ResponseWrapper(localName = "updateProductResponse", targetNamespace = "http://webServices/",
                     className = "webservices.UpdateProductResponse")
    @Action(input = "http://webServices/ProductWebService/updateProductRequest",
            output = "http://webServices/ProductWebService/updateProductResponse")
    public boolean updateProduct(@WebParam(name = "arg0", targetNamespace = "") int arg0,
                                 @WebParam(name = "arg1", targetNamespace = "") Product arg1);

    /**
     *
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "insertProduct", targetNamespace = "http://webServices/",
                    className = "webservices.InsertProduct")
    @ResponseWrapper(localName = "insertProductResponse", targetNamespace = "http://webServices/",
                     className = "webservices.InsertProductResponse")
    @Action(input = "http://webServices/ProductWebService/insertProductRequest",
            output = "http://webServices/ProductWebService/insertProductResponse")
    public boolean insertProduct(@WebParam(name = "arg0", targetNamespace = "") Product arg0);

    /**
     *
     * @param arg0
     * @return
     *     returns webservices.Product
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findProduct", targetNamespace = "http://webServices/",
                    className = "webservices.FindProduct")
    @ResponseWrapper(localName = "findProductResponse", targetNamespace = "http://webServices/",
                     className = "webservices.FindProductResponse")
    @Action(input = "http://webServices/ProductWebService/findProductRequest",
            output = "http://webServices/ProductWebService/findProductResponse")
    public Product findProduct(@WebParam(name = "arg0", targetNamespace = "") int arg0);

    /**
     *
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "deleteProduct", targetNamespace = "http://webServices/",
                    className = "webservices.DeleteProduct")
    @ResponseWrapper(localName = "deleteProductResponse", targetNamespace = "http://webServices/",
                     className = "webservices.DeleteProductResponse")
    @Action(input = "http://webServices/ProductWebService/deleteProductRequest",
            output = "http://webServices/ProductWebService/deleteProductResponse")
    public boolean deleteProduct(@WebParam(name = "arg0", targetNamespace = "") int arg0);

    /**
     *
     * @return
     *     returns java.util.List<webservices.Product>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listAllProducts", targetNamespace = "http://webServices/",
                    className = "webservices.ListAllProducts")
    @ResponseWrapper(localName = "listAllProductsResponse", targetNamespace = "http://webServices/",
                     className = "webservices.ListAllProductsResponse")
    @Action(input = "http://webServices/ProductWebService/listAllProductsRequest",
            output = "http://webServices/ProductWebService/listAllProductsResponse")
    public List<Product> listAllProducts();

}
