
package webservices;

import java.util.List;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;

import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10-b140319.1121
 * Generated source version: 2.2
 *
 */
@WebService(name = "ProductRegistrationWebService", targetNamespace = "http://webServices/")
@XmlSeeAlso({ ObjectFactory.class })
public interface ProductRegistrationWebService {


    /**
     *
     * @return
     *     returns java.util.List<webservices.ProductRegistration>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listAllProductRegistrationsService", targetNamespace = "http://webServices/",
                    className = "webservices.ListAllProductRegistrationsService")
    @ResponseWrapper(localName = "listAllProductRegistrationsServiceResponse", targetNamespace = "http://webServices/",
                     className = "webservices.ListAllProductRegistrationsServiceResponse")
    @Action(input = "http://webServices/ProductRegistrationWebService/listAllProductRegistrationsServiceRequest",
            output = "http://webServices/ProductRegistrationWebService/listAllProductRegistrationsServiceResponse")
    public List<ProductRegistration> listAllProductRegistrationsService();

    /**
     *
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "insertProductRegistration", targetNamespace = "http://webServices/",
                    className = "webservices.InsertProductRegistration")
    @ResponseWrapper(localName = "insertProductRegistrationResponse", targetNamespace = "http://webServices/",
                     className = "webservices.InsertProductRegistrationResponse")
    @Action(input = "http://webServices/ProductRegistrationWebService/insertProductRegistrationRequest",
            output = "http://webServices/ProductRegistrationWebService/insertProductRegistrationResponse")
    public boolean insertProductRegistration(@WebParam(name = "arg0", targetNamespace = "") ProductRegistration arg0);

    /**
     *
     * @param arg1
     * @param arg0
     * @return
     *     returns webservices.ProductRegistration
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findProductRegistration", targetNamespace = "http://webServices/",
                    className = "webservices.FindProductRegistration")
    @ResponseWrapper(localName = "findProductRegistrationResponse", targetNamespace = "http://webServices/",
                     className = "webservices.FindProductRegistrationResponse")
    @Action(input = "http://webServices/ProductRegistrationWebService/findProductRegistrationRequest",
            output = "http://webServices/ProductRegistrationWebService/findProductRegistrationResponse")
    public ProductRegistration findProductRegistration(@WebParam(name = "arg0", targetNamespace = "") int arg0,
                                                       @WebParam(name = "arg1", targetNamespace = "") int arg1);

    /**
     *
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "updateProductRegistration", targetNamespace = "http://webServices/",
                    className = "webservices.UpdateProductRegistration")
    @ResponseWrapper(localName = "updateProductRegistrationResponse", targetNamespace = "http://webServices/",
                     className = "webservices.UpdateProductRegistrationResponse")
    @Action(input = "http://webServices/ProductRegistrationWebService/updateProductRegistrationRequest",
            output = "http://webServices/ProductRegistrationWebService/updateProductRegistrationResponse")
    public boolean updateProductRegistration(@WebParam(name = "arg0", targetNamespace = "") int arg0,
                                             @WebParam(name = "arg1", targetNamespace = "") int arg1,
                                             @WebParam(name = "arg2", targetNamespace = "") ProductRegistration arg2);

    /**
     *
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "deleteProductRegistration", targetNamespace = "http://webServices/",
                    className = "webservices.DeleteProductRegistration")
    @ResponseWrapper(localName = "deleteProductRegistrationResponse", targetNamespace = "http://webServices/",
                     className = "webservices.DeleteProductRegistrationResponse")
    @Action(input = "http://webServices/ProductRegistrationWebService/deleteProductRegistrationRequest",
            output = "http://webServices/ProductRegistrationWebService/deleteProductRegistrationResponse")
    public boolean deleteProductRegistration(@WebParam(name = "arg0", targetNamespace = "") int arg0,
                                             @WebParam(name = "arg1", targetNamespace = "") int arg1);

}
