
package webservices;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10-b140319.1121
 * Generated source version: 2.2
 *
 */
@WebServiceClient(name = "ProductRegistrationWebServiceSW", targetNamespace = "http://webServices/",
                  wsdlLocation =
                  "http://localhost:7101/ServerBankSW/ProductRegistrationWebServicePort?WSDL#%7Bhttp%3A%2F%2FwebServices%2F%7DProductRegistrationWebServiceSW")
public class ProductRegistrationWebServiceSW extends Service {

    private final static URL PRODUCTREGISTRATIONWEBSERVICESW_WSDL_LOCATION;
    private final static WebServiceException PRODUCTREGISTRATIONWEBSERVICESW_EXCEPTION;
    private final static QName PRODUCTREGISTRATIONWEBSERVICESW_QNAME =
        new QName("http://webServices/", "ProductRegistrationWebServiceSW");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url =
                new URL("http://localhost:7101/ServerBankSW/ProductRegistrationWebServicePort?WSDL#%7Bhttp%3A%2F%2FwebServices%2F%7DProductRegistrationWebServiceSW");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PRODUCTREGISTRATIONWEBSERVICESW_WSDL_LOCATION = url;
        PRODUCTREGISTRATIONWEBSERVICESW_EXCEPTION = e;
    }

    public ProductRegistrationWebServiceSW() {
        super(__getWsdlLocation(), PRODUCTREGISTRATIONWEBSERVICESW_QNAME);
    }

    public ProductRegistrationWebServiceSW(WebServiceFeature... features) {
        super(__getWsdlLocation(), PRODUCTREGISTRATIONWEBSERVICESW_QNAME, features);
    }

    public ProductRegistrationWebServiceSW(URL wsdlLocation) {
        super(wsdlLocation, PRODUCTREGISTRATIONWEBSERVICESW_QNAME);
    }

    public ProductRegistrationWebServiceSW(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PRODUCTREGISTRATIONWEBSERVICESW_QNAME, features);
    }

    public ProductRegistrationWebServiceSW(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ProductRegistrationWebServiceSW(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns ProductRegistrationWebService
     */
    @WebEndpoint(name = "ProductRegistrationWebServicePort")
    public ProductRegistrationWebService getProductRegistrationWebServicePort() {
        return super.getPort(new QName("http://webServices/", "ProductRegistrationWebServicePort"),
                             ProductRegistrationWebService.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ProductRegistrationWebService
     */
    @WebEndpoint(name = "ProductRegistrationWebServicePort")
    public ProductRegistrationWebService getProductRegistrationWebServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webServices/", "ProductRegistrationWebServicePort"),
                             ProductRegistrationWebService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PRODUCTREGISTRATIONWEBSERVICESW_EXCEPTION != null) {
            throw PRODUCTREGISTRATIONWEBSERVICESW_EXCEPTION;
        }
        return PRODUCTREGISTRATIONWEBSERVICESW_WSDL_LOCATION;
    }

}
